
package com.bibliotheque.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BibliothequeServiceService", targetNamespace = "http://service.bibliotheque.com/", wsdlLocation = "http://localhost:8089/biblio?wsdl")
public class BibliothequeServiceService
    extends Service
{

    private final static URL BIBLIOTHEQUESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BIBLIOTHEQUESERVICESERVICE_EXCEPTION;
    private final static QName BIBLIOTHEQUESERVICESERVICE_QNAME = new QName("http://service.bibliotheque.com/", "BibliothequeServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/biblio?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BIBLIOTHEQUESERVICESERVICE_WSDL_LOCATION = url;
        BIBLIOTHEQUESERVICESERVICE_EXCEPTION = e;
    }

    public BibliothequeServiceService() {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICESERVICE_QNAME);
    }

    public BibliothequeServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BIBLIOTHEQUESERVICESERVICE_QNAME, features);
    }

    public BibliothequeServiceService(URL wsdlLocation) {
        super(wsdlLocation, BIBLIOTHEQUESERVICESERVICE_QNAME);
    }

    public BibliothequeServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BIBLIOTHEQUESERVICESERVICE_QNAME, features);
    }

    public BibliothequeServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BibliothequeServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliothequeWS
     */
    @WebEndpoint(name = "BibliothequeWSPort")
    public BibliothequeWS getBibliothequeWSPort() {
        return super.getPort(new QName("http://service.bibliotheque.com/", "BibliothequeWSPort"), BibliothequeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliothequeWS
     */
    @WebEndpoint(name = "BibliothequeWSPort")
    public BibliothequeWS getBibliothequeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bibliotheque.com/", "BibliothequeWSPort"), BibliothequeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BIBLIOTHEQUESERVICESERVICE_EXCEPTION!= null) {
            throw BIBLIOTHEQUESERVICESERVICE_EXCEPTION;
        }
        return BIBLIOTHEQUESERVICESERVICE_WSDL_LOCATION;
    }

}
