
package com.bibliotheque.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BibliothequeException", targetNamespace = "http://service.bibliotheque.com/")
public class BibliothequeException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private BibliothequeException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public BibliothequeException_Exception(String message, BibliothequeException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public BibliothequeException_Exception(String message, BibliothequeException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bibliotheque.service.BibliothequeException
     */
    public BibliothequeException getFaultInfo() {
        return faultInfo;
    }

}
