
package com.bibliotheque.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliothequeWS", targetNamespace = "http://service.bibliotheque.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliothequeWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.bibliotheque.service.Ouvrage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOuvrage", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetOuvrage")
    @ResponseWrapper(localName = "getOuvrageResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetOuvrageResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getOuvrageRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getOuvrageResponse")
    public Ouvrage getOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param mail
     * @param utilisateurId
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "saveMail", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.SaveMail")
    @ResponseWrapper(localName = "saveMailResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.SaveMailResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/saveMailRequest", output = "http://service.bibliotheque.com/BibliothequeWS/saveMailResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/saveMail/Fault/BibliothequeException")
    })
    public void saveMail(
        @WebParam(name = "mail", targetNamespace = "")
        Mail mail,
        @WebParam(name = "utilisateur_id", targetNamespace = "")
        Long utilisateurId)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteOuvrage", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteOuvrage")
    @ResponseWrapper(localName = "deleteOuvrageResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteOuvrageResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/deleteOuvrageRequest", output = "http://service.bibliotheque.com/BibliothequeWS/deleteOuvrageResponse")
    public void deleteOuvrage(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param disponnible
     * @param size
     * @param motCle
     * @param genre
     * @param page
     * @return
     *     returns com.bibliotheque.service.PageOuvrage
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listOuvrage", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.ListOuvrage")
    @ResponseWrapper(localName = "listOuvrageResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.ListOuvrageResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/listOuvrageRequest", output = "http://service.bibliotheque.com/BibliothequeWS/listOuvrageResponse")
    public PageOuvrage listOuvrage(
        @WebParam(name = "mot-cle", targetNamespace = "")
        String motCle,
        @WebParam(name = "genre", targetNamespace = "")
        String genre,
        @WebParam(name = "disponnible", targetNamespace = "")
        boolean disponnible,
        @WebParam(name = "page", targetNamespace = "")
        int page,
        @WebParam(name = "size", targetNamespace = "")
        int size);

    /**
     * 
     * @return
     *     returns java.util.List<com.bibliotheque.service.Genre>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListGenre", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListGenre")
    @ResponseWrapper(localName = "getListGenreResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListGenreResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getListGenreRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getListGenreResponse")
    public List<Genre> getListGenre();

    /**
     * 
     * @param utilisateurId
     * @return
     *     returns com.bibliotheque.service.Mail
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMail", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetMail")
    @ResponseWrapper(localName = "getMailResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetMailResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getMailRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getMailResponse")
    public Mail getMail(
        @WebParam(name = "utilisateur_id", targetNamespace = "")
        Long utilisateurId);

    /**
     * 
     * @param pseudo
     * @return
     *     returns java.util.List<com.bibliotheque.service.Roles>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListRoles", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListRoles")
    @ResponseWrapper(localName = "getListRolesResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListRolesResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getListRolesRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getListRolesResponse")
    public List<Roles> getListRoles(
        @WebParam(name = "pseudo", targetNamespace = "")
        String pseudo);

    /**
     * 
     * @param ouvrage
     * @param genre
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createOuvrage", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateOuvrage")
    @ResponseWrapper(localName = "createOuvrageResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateOuvrageResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/createOuvrageRequest", output = "http://service.bibliotheque.com/BibliothequeWS/createOuvrageResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/createOuvrage/Fault/BibliothequeException")
    })
    public void createOuvrage(
        @WebParam(name = "ouvrage", targetNamespace = "")
        Ouvrage ouvrage,
        @WebParam(name = "genre", targetNamespace = "")
        String genre)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param id
     * @return
     *     returns com.bibliotheque.service.Utilisateur
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUtilisateur", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetUtilisateur")
    @ResponseWrapper(localName = "getUtilisateurResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetUtilisateurResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getUtilisateurRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getUtilisateurResponse")
    public Utilisateur getUtilisateur(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param utilisateur
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "saveUtilisateur", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.SaveUtilisateur")
    @ResponseWrapper(localName = "saveUtilisateurResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.SaveUtilisateurResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/saveUtilisateurRequest", output = "http://service.bibliotheque.com/BibliothequeWS/saveUtilisateurResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/saveUtilisateur/Fault/BibliothequeException")
    })
    public void saveUtilisateur(
        @WebParam(name = "utilisateur", targetNamespace = "")
        Utilisateur utilisateur)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param passWord
     * @param pseudo
     * @return
     *     returns com.bibliotheque.service.Utilisateur
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doConnection", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DoConnection")
    @ResponseWrapper(localName = "doConnectionResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DoConnectionResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/doConnectionRequest", output = "http://service.bibliotheque.com/BibliothequeWS/doConnectionResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/doConnection/Fault/BibliothequeException")
    })
    public Utilisateur doConnection(
        @WebParam(name = "pseudo", targetNamespace = "")
        String pseudo,
        @WebParam(name = "passWord", targetNamespace = "")
        String passWord)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param ouvrage
     * @param genre
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateOuvrage", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.UpdateOuvrage")
    @ResponseWrapper(localName = "updateOuvrageResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.UpdateOuvrageResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/updateOuvrageRequest", output = "http://service.bibliotheque.com/BibliothequeWS/updateOuvrageResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/updateOuvrage/Fault/BibliothequeException")
    })
    public void updateOuvrage(
        @WebParam(name = "ouvrage", targetNamespace = "")
        Ouvrage ouvrage,
        @WebParam(name = "genre", targetNamespace = "")
        String genre)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bibliotheque.service.Reservation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReservation", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetReservation")
    @ResponseWrapper(localName = "getReservationResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetReservationResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getReservationRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getReservationResponse")
    public Reservation getReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "prolongerReservation", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.ProlongerReservation")
    @ResponseWrapper(localName = "prolongerReservationResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.ProlongerReservationResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/prolongerReservationRequest", output = "http://service.bibliotheque.com/BibliothequeWS/prolongerReservationResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/prolongerReservation/Fault/BibliothequeException")
    })
    public void prolongerReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Long arg1)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUtilisateur", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteUtilisateur")
    @ResponseWrapper(localName = "deleteUtilisateurResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteUtilisateurResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/deleteUtilisateurRequest", output = "http://service.bibliotheque.com/BibliothequeWS/deleteUtilisateurResponse")
    public void deleteUtilisateur(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteReservation", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteReservation")
    @ResponseWrapper(localName = "deleteReservationResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.DeleteReservationResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/deleteReservationRequest", output = "http://service.bibliotheque.com/BibliothequeWS/deleteReservationResponse")
    public void deleteReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param mail
     * @param utilisateur
     * @return
     *     returns com.bibliotheque.service.Utilisateur
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createUtilisateur", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateUtilisateur")
    @ResponseWrapper(localName = "createUtilisateurResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateUtilisateurResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/createUtilisateurRequest", output = "http://service.bibliotheque.com/BibliothequeWS/createUtilisateurResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/createUtilisateur/Fault/BibliothequeException")
    })
    public Utilisateur createUtilisateur(
        @WebParam(name = "utilisateur", targetNamespace = "")
        Utilisateur utilisateur,
        @WebParam(name = "mail", targetNamespace = "")
        Mail mail)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDaysProlongation", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetDaysProlongation")
    @ResponseWrapper(localName = "getDaysProlongationResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetDaysProlongationResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getDaysProlongationRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getDaysProlongationResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/getDaysProlongation/Fault/BibliothequeException")
    })
    public int getDaysProlongation()
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param reservation
     * @param utilisateurId
     * @param ouvrageId
     * @throws BibliothequeException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "createReservation", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateReservation")
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.CreateReservationResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/createReservationRequest", output = "http://service.bibliotheque.com/BibliothequeWS/createReservationResponse", fault = {
        @FaultAction(className = BibliothequeException_Exception.class, value = "http://service.bibliotheque.com/BibliothequeWS/createReservation/Fault/BibliothequeException")
    })
    public void createReservation(
        @WebParam(name = "reservation", targetNamespace = "")
        Reservation reservation,
        @WebParam(name = "ouvrage_id", targetNamespace = "")
        Long ouvrageId,
        @WebParam(name = "utilisateur_id", targetNamespace = "")
        Long utilisateurId)
        throws BibliothequeException_Exception
    ;

    /**
     * 
     * @param utilisateurId
     * @return
     *     returns java.util.List<com.bibliotheque.service.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListReservationByUtilisateurID", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListReservationByUtilisateurID")
    @ResponseWrapper(localName = "getListReservationByUtilisateurIDResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListReservationByUtilisateurIDResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getListReservationByUtilisateurIDRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getListReservationByUtilisateurIDResponse")
    public List<Reservation> getListReservationByUtilisateurID(
        @WebParam(name = "utilisateur_id", targetNamespace = "")
        Long utilisateurId);

    /**
     * 
     * @param utilisateurId
     * @return
     *     returns java.util.List<com.bibliotheque.service.Reservation>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListReservationRetardedByUtilisateurID", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListReservationRetardedByUtilisateurID")
    @ResponseWrapper(localName = "getListReservationRetardedByUtilisateurIDResponse", targetNamespace = "http://service.bibliotheque.com/", className = "com.bibliotheque.service.GetListReservationRetardedByUtilisateurIDResponse")
    @Action(input = "http://service.bibliotheque.com/BibliothequeWS/getListReservationRetardedByUtilisateurIDRequest", output = "http://service.bibliotheque.com/BibliothequeWS/getListReservationRetardedByUtilisateurIDResponse")
    public List<Reservation> getListReservationRetardedByUtilisateurID(
        @WebParam(name = "utilisateur_id", targetNamespace = "")
        Long utilisateurId);

}
